//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        [EmailAddress]
        public string emailId { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:DD-MM-yyyy}")]
        public DateTime Doj { get; set; }
        [MinLength(8),MaxLength(16)]
        public string Password { get; set; }
    }
}
